name: "RapidAPI OpenAPI"
description: "Auto update RapidAPI OpenAPI documentation"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  rapidapi_api_key:
    description: "Your RapiAPI API Key"
    required: true
    default: ""
  rapidapi_api_id:
    description: "Your RapiAPI API ID"
    required: true
    default: ""
  openapi_file:
    description: "Your OpenAPI file to use for update"
    required: false
    default: "openapi.json"
  default_server_url:
    description: "You can provide a default server url"
    required: false
    default: ""
runs:
  using: "node16"
  main: "index.js"
