name: "RapidAPI OpenAPI"
description: "Auto update RapidAPI OpenAPI documentation"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  rapidapi-api-key:
    description: "Your RapiAPI API Key"
    required: true
    default: ""
  rapidapi-api-id:
    description: "Your RapiAPI API ID"
    required: true
    default: ""
  openapi-file:
    description: "Your OpenAPI file to use for update"
    required: false
    default: "openapi.json"
  default-server-url:
    description: "You can provide a default server url"
    required: false
    default: ""
runs:
  using: "node12"
  main: "index.js"
